# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(1080, 853)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditLink = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLink.setGeometry(QtCore.QRect(60, 110, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditLink.setFont(font)
        self.lineEditLink.setObjectName("lineEditLink")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath.setGeometry(QtCore.QRect(70, 360, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPath.setFont(font)
        self.lineEditPath.setText("")
        self.lineEditPath.setObjectName("lineEditPath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 310, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.buttonPath = QtWidgets.QToolButton(self.centralwidget)
        self.buttonPath.setGeometry(QtCore.QRect(710, 360, 31, 31))
        self.buttonPath.setObjectName("buttonPath")
        self.buttonDownload = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDownload.setGeometry(QtCore.QRect(840, 660, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDownload.setFont(font)
        self.buttonDownload.setObjectName("buttonDownload")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 440, 671, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 510, 681, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.graphicsView.setFont(font)
        self.graphicsView.setObjectName("graphicsView")
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.setGeometry(QtCore.QRect(80, 520, 651, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("color: rgb(255, 0, 0)")
        self.labelError.setText("")
        self.labelError.setTextFormat(QtCore.Qt.PlainText)
        self.labelError.setScaledContents(False)
        self.labelError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelError.setWordWrap(True)
        self.labelError.setIndent(2)
        self.labelError.setOpenExternalLinks(False)
        self.labelError.setObjectName("labelError")
        self.labelVideoTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelVideoTitle.setGeometry(QtCore.QRect(60, 210, 861, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelVideoTitle.setFont(font)
        self.labelVideoTitle.setStyleSheet("color: rgb(0, 226, 109)")
        self.labelVideoTitle.setText("")
        self.labelVideoTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelVideoTitle.setObjectName("labelVideoTitle")
        Ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        Ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "MainWindow"))
        self.label.setText(_translate("Ui_MainWindow", "Add link of the video:"))
        self.label_2.setText(_translate("Ui_MainWindow", "Choose path where to download:"))
        self.buttonPath.setText(_translate("Ui_MainWindow", "..."))
        self.buttonDownload.setText(_translate("Ui_MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Ui_MainWindow()
    ui.setupUi(Ui_MainWindow)
    Ui_MainWindow.show()
    sys.exit(app.exec_())
